[package]
name = "sprite_tools"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
flatbuffers = "24.3"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
